name: GitHub Package Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.5'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@fieldlevel'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

