name: Lint Codebase

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.17'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts
      - name: Run ESLint
        run: yarn lint