name: Lint Codebase

on:
  pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.5'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run ESLint
        run: npm run lint